"""Offline OpenAPI + response-type export; no server, network or extra packages.

This intentionally supports the schema vocabulary used by this API and refuses
unknown shapes rather than silently generating an unsafe TypeScript type.
"""
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.main import create_app

FRONTEND = Path(__file__).resolve().parents[2] / "frontend"


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    for key, joiner in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        if key in schema:
            return "(" + joiner.join(ts_type(part) for part in schema[key]) + ")"
    kind = schema.get("type")
    if kind in ("string", "boolean", "null"):
        return kind
    if kind in ("integer", "number"):
        return "number"
    if kind == "array":
        return f"Array<{ts_type(schema['items'])}>"
    if kind == "object":
        fields = []
        required = schema.get("required", [])
        for name, value in schema.get("properties", {}).items():
            optional = "" if name in required else "?"
            fields.append(f"{json.dumps(name)}{optional}: {ts_type(value)};")
        extra = schema.get("additionalProperties")
        if extra:
            fields.append(f"[key: string]: {ts_type(extra) if isinstance(extra, dict) else 'unknown'};")
        return "{ " + " ".join(fields) + " }" if fields else "Record<string, unknown>"
    if not (schema.keys() - {"title", "description", "default", "examples"}):
        return "unknown"
    raise ValueError(f"Unsupported schema shape: {sorted(schema)}")


def artifacts() -> dict[Path, str]:
    schema = create_app().openapi()
    definitions = schema["components"]["schemas"]
    lines = ["// Generated by backend/scripts/export_openapi.py. Do not edit."]
    for name, definition in sorted(definitions.items()):
        lines.append(f"export type {name} = {ts_type(definition)};")
    return {FRONTEND / "openapi.json": json.dumps(schema, indent=2, sort_keys=True) + "\n",
            FRONTEND / "lib/api-types.ts": "\n".join(lines) + "\n"}


if __name__ == "__main__":
    for path, content in artifacts().items():
        if "--check" in sys.argv:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Generated contract drift: {path.name}; run npm run gen:types")
        else:
            path.write_text(content)
    print("OpenAPI and TypeScript contracts are current.")